name: Event Registration System - TS Version

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            MODE: dev
            PORT: 3000
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            MONGO_URI_ONLINE: ${{ secrets.MONGO_URI_ONLINE }}
            MONGO_URI_OFFLINE: ${{ secrets.MONGO_URI_OFFLINE }}
            STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
            FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_CONFIG_ENCRYPT_KEY: ${{ secrets.FIREBASE_CONFIG_ENCRYPT_KEY }}

        steps:
            - name: Chekout code
              uses: actions/checkout@v3

            # - name: Install node required
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 14.x

            # - name: Start MongoDB
            #   uses: supercharge/mongodb-github-action@1.8.0
            #   with:
            #       mongodb-version: "6.0"

            - name: Check if secret exists
              run: |
                  if [[ -n "${{ secrets.FIREBASE_API_KEY }}" ]]; then
                    echo "Secret exists"
                  else
                    echo "Secret does not exist"
                  fi

            - name: Print secret
              run: |
                  echo $FIREBASE_API_KEY
                  echo $FIREBASE_CONFIG_ENCRYPT_KEY
                  echo $JWT_SECRET

            # - name: Decrypt Firebase permission file
            #   run: |
            #       echo $FIREBASE_CONFIG_ENCRYPT_KEY
            #       openssl enc -d -aes-256-cbc -in ts/src/config/encrypted-firebase.json.enc -out ts/src/config/firebase.json -pass env:FIREBASE_CONFIG_ENCRYPT_KEY -pbkdf2

            # - name: Install dependencies
            #   run: |
            #       cd ts
            #       npm install

            # - name: Run tests
            #   run: |
            #       cd ts
            #       ls src/config/
            #       npm test
